# Generated by Django 3.2.9 on 2021-11-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teach_id',
            new_name='id_t',
        ),
    ]
