# Generated by Django 3.2.9 on 2021-11-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_rename_teach_id_teacher_id_t'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name_t',
        ),
    ]
