# Generated by Django 3.2.9 on 2021-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolApp', '0005_auto_20211107_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('branches', models.CharField(max_length=25)),
                ('teachers', models.CharField(max_length=500)),
            ],
        ),
    ]
